# this file don't actual data, its all rewrite to start make start or make up command
route:
    receiver: 'default-receiver'

receivers:
    - name: 'default-receiver'
      email_configs:
          - send_resolved: true
            to: '$EMAIL_ADRESS_FOR_SEND_ALERT'
            from: '$APP_SITE'
            smarthost: '$HOSTNAME_SMTP_SERVER:$SMTP_PORT'
            auth_username: '$USERNAME_SMTP_ALERT'
            auth_password: '$PASSWORD_SMTP_ALERT'
            auth_identity: '$SMTP_AUTH_IDENTITY'
