global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # https://stackoverflow.com/a/67158212
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  # https://github.com/Sqooba/prometheus-docker-labels-discovery
  - job_name: 'docker-labels-sd'
    file_sd_configs:
    - files:
      - 'from-docker-labels.json'

remote_write:
    - url: "http://storage:9201/write"
remote_read:
    - url: "http://storage:9201/read"
